### ISSUE TITLE
crash on reconnect invitationtracker

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#305]
```
2021-05-24 08:51:16 INFO  Main:16 - Init System
2021-05-24 08:51:17 INFO  JDA:300 - Login Successful!
2021-05-24 08:51:17 INFO  WebSocketClient:364 - Connected to WebSocket
2021-05-24 08:51:20 ERROR WebSocketClient:491 - Encountered IDENTIFY Rate Limit!
2021-05-24 08:51:20 WARN  WebSocketClient:494 - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue
2021-05-24 08:51:25 ERROR SessionControllerAdapter:186 - Worker has failed with throwable!
java.lang.NoClassDefFoundError: org/slf4j/MDC$MDCCloseable
        at net.dv8tion.jda.internal.requests.WebSocketClient.reconnect(WebSocketClient.java:548)
        at net.dv8tion.jda.internal.requests.WebSocketClient$ReconnectNode.run(WebSocketClient.java:1349)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.processQueue(SessionControllerAdapter.java:222)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.run(SessionControllerAdapter.java:205)
Caused by: java.lang.ClassNotFoundException: org.slf4j.MDC$MDCCloseable
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 4 more

```

**Comment by zaanposni** [comment]
seems to be fixed in commit [644d186](https://github.com/zaanposni/discord-masz/commit/644d186293c2b6c970c85138521fb7611f515da4).
Closing for now... 👀
