### ISSUE TITLE
userscan fails if bot is no member of registered guild

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#497]
userscan fails if bot is no member of registered guild

```
Object reference not set to an instance of an object.
   at MASZ.Models.Views.DiscordGuildView..ctor(IGuild guild) in /app/MASZ/Models/Views/Discord/DiscordGuildView.cs:line 15
   at MASZ.Controllers.UserNetworkController.GetUserNetwork(UInt64 userId) in /app/MASZ/Controllers/api/v1/Views/UserNetworkController.cs:line 38
```

@FeroxFoxxo we should fix this in the next release

**Comment by zaanposni** [comment]
fixed in v2.7.0 branch
